version: '2'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres:10.3
    container_name: crm-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel

  redis:
    image: redis:4.0
    container_name: crm-redis
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: crm-nginx
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8002:80"

  php-fpm:
    build: docker/php-fpm
    container_name: crm-php-fpm
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini